services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    user: "1000:1000"
    ports:
      - 3000:3000
      - 6006:6006
    tty: true
    stdin_open: true
    volumes:
      - ./src:/home/node/practice